# Generated by Django 3.2 on 2023-04-27 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptsEncouragement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='traininglog',
            name='train_skd',
        ),
        migrations.RemoveField(
            model_name='traininglog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='train_cat',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='train_goal',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='weekly_skd',
        ),
        migrations.RemoveField(
            model_name='traininglevel',
            name='four_day_workout',
        ),
        migrations.RemoveField(
            model_name='traininglevel',
            name='hierarchy',
        ),
        migrations.RemoveField(
            model_name='traininglevel',
            name='three_day_workout',
        ),
        migrations.RemoveField(
            model_name='traininglevel',
            name='train_cat',
        ),
        migrations.RemoveField(
            model_name='traininglevel',
            name='two_day_workout',
        ),
        migrations.RemoveField(
            model_name='trainingpreference',
            name='train_plan',
        ),
        migrations.RemoveField(
            model_name='trainingpreference',
            name='workout_day',
        ),
        migrations.RemoveField(
            model_name='trainingschedule',
            name='daily_task',
        ),
        migrations.RemoveField(
            model_name='trainingschedule',
            name='is_achieved',
        ),
        migrations.AddField(
            model_name='traininglevel',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingpreference',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='friday_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='friday_pace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='friday_workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='is_complete_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='is_complete_monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='is_complete_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='is_complete_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='is_complete_thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='is_complete_tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='is_complete_wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='monday_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='monday_pace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='monday_workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='saturday_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='saturday_pace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='saturday_workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='skd_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='sunday_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='sunday_pace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='sunday_workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='thursday_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='thursday_pace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='thursday_workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='train_pref',
            field=models.ManyToManyField(blank=True, to='api.TrainingPreference'),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='tuesday_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='tuesday_pace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='tuesday_workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='wednesday_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='wednesday_pace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='wednesday_workout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainingpreference',
            name='current_train_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.traininglevel'),
        ),
        migrations.AlterField(
            model_name='trainingpreference',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainingpreference',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainingpreference',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainingpreference',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainingpreference',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainingpreference',
            name='train_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trainingcategory'),
        ),
        migrations.AlterField(
            model_name='trainingpreference',
            name='train_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.traininggoal'),
        ),
        migrations.AlterField(
            model_name='trainingpreference',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainingpreference',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DailyTask',
        ),
        migrations.DeleteModel(
            name='TrainingLog',
        ),
        migrations.DeleteModel(
            name='TrainingPlan',
        ),
    ]
